name: Release filigran-chatbot

on:
  push:
    tags:
      - '*'

jobs:
  release-chatbot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          echo "Starting release version ${{ github.ref }}"
          #Disable auto tag from yarn since we already have a git tag
          yarn config set version-git-tag false
          yarn version --new-version ${{ github.ref }}
          yarn install
          yarn pack --out filigran-chatbot-${{ github.ref }}.tgz
          ls -lart
          pwd
          gh release create ${{ github.ref }} filigran-chatbot-*.tgz
        env:
          GITHUB_TOKEN: ${{ github.token }}